### ISSUE TITLE
No Dist folder 

### ISSUE THREAD

**Issue by xandorxicay** [Sibiraj-S/angularjs-toast#10]
dont see dist folder with the compile styles.

**Comment by Sibiraj-S** [comment]
Yes. Since bower is deprecated there ia no point in having the dist folder. Only the source is available in the repository. The compiled output are published directly to npm. You can either install it using`npm install angularjs-toast` or use the cdn

```
//unpkg.com/angularjs-toast@latest/angularjs-toast.js
//unpkg.com/angularjs-toast@latest/angularjs-toast.css
```.

**Comment by Sibiraj-S** [comment]
@xandorxicay . did your query resolve?

**Comment by Sibiraj-S** [comment]
closing this issue for now.
