### ISSUE TITLE
html strings are interpreted literally

### ISSUE THREAD

**Issue by atoy3731** [Sibiraj-S/angularjs-toast#6]
It looks like trying to use HTML strings as the message always interprets them literally, I'm guessing due to ng-sanitize.

![html-literal](https://user-images.githubusercontent.com/5939985/31892998-5a7bda8a-b7d8-11e7-968c-da42ad7790c5.png)

**Comment by Sibiraj-S** [comment]
fixed now. HTML is now parsed correctly
